#! /bin/sh

### BEGIN INIT INFO
# Provides:		mx_router
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	Startet die initialen Scripte des mx_router
### END INIT INFO

# Version: 1

set -e

START_SCRIPT="/opt/mx_router/start.sh"
STOP_SCRIPT="/opt/mx_router/start.sh"

test -x $START_SCRIPT || exit 1
test -x $STOP_SCRIPT || exit 1

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting mx_router $START_SCRIPT" "mx_router"
        $START_SCRIPT
        if [ $? -eq 0 ]; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;
  stop)
	log_daemon_msg "Stopping mx_router $STOP_SCRIPT" "mx_router"
        $STOP_SCRIPT
        if [ $? -eq 0 ]; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;
  restart)
        $0 stop && sleep 2 && $0 start
        ;;
  *)
	log_action_msg "Usage: /etc/init.d/mx_router {start|stop}"
	exit 1
esac

exit 0

